name: Generate statistics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Increase disk space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
    
      - name: Checkout .github
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout forumPosts archive
        uses: actions/checkout@v4
        with:
          ref: main
          repository: deeeepio-archive/forumPosts
          path: forumPosts

      - name: Checkout maps archive
        uses: actions/checkout@v4
        with:
          ref: main
          repository: deeeepio-archive/maps
          path: maps

      - name: Checkout playHistories archive
        uses: actions/checkout@v4
        with:
          ref: main
          repository: deeeepio-archive/playHistories
          path: playHistories

      - name: Checkout users archive
        uses: actions/checkout@v4
        with:
          ref: main
          repository: deeeepio-archive/users
          path: users

      - name: Count files
        run: |
          echo "Forum posts: $(find forumPosts -type f | wc -l | sed -r ':L;s=\b([0-9]+)([0-9]{3})\b=\1,\2=g;t L') files ($(du -sh --exclude=.git/** forumPosts | grep -oE '[0-9.]+[A-Za-z]+?'))  " >> stats
          echo "Maps: $(find maps -type f | wc -l | sed -r ':L;s=\b([0-9]+)([0-9]{3})\b=\1,\2=g;t L') files ($(du -sh --exclude=.git/** maps | grep -oE '[0-9.]+[A-Za-z]+?'))  " >> stats
          echo "Play histories: $(find playHistories -type f | wc -l | sed -r ':L;s=\b([0-9]+)([0-9]{3})\b=\1,\2=g;t L') files ($(du -sh --exclude=.git/** playHistories | grep -oE '[0-9.]+[A-Za-z]+?'))  " >> stats
          echo "Users: $(find users -type f | wc -l | sed -r ':L;s=\b([0-9]+)([0-9]{3})\b=\1,\2=g;t L') files ($(du -sh --exclude=.git/** users | grep -oE '[0-9.]+[A-Za-z]+?'))  " >> stats

      - name: Update README
        run: |
          npm run generate:stats

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update statistics
